### ISSUE TITLE
Code showing prototypes related between classes / PrototypeGraph incomplete as well as other experiments in the paper

### ISSUE THREAD

**Issue by PoulamiSM** [gmum/ProtoPool#2]
Hello,
I appreciate the very intuitive work done in the paper. Thanks :)
While going through the codebase, I found code corresponding to many experiments missing. 
For ex: the class definition of 'PrototypeGraph' imported from model.py is missing as well as the graph_visualisation notebook only shows the code for MNIST dataset which is not used in the paper. How about updating with birds/cars dataset? It is very difficult to validate the results  shown in paper without visualising the impact of shared prototypes.
As well as all the code for all the experiments and ablation shown in paper is missing/incomplete.
Do you have plans to update the code soon? 

Thanks!

**Comment by dawrym** [comment]
We do not plan to share more codes. It is enough to train a model and obtain analogical results as reported in the paper.
