### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by TeodorChiaburu** [gmum/ProtoPool#3]
Hello! 
Thank you for your great contribution!
I have successfully trained your model on my custom dataset. Any hints on how I may best run inference now with it, so that I can yield prototype explanations for test images?
Thank you and kind regards!

**Comment by dawrym** [comment]
You need to perform a push operation to generate the prototypes. They will be saved in a given subfolder. Then, when you do inference, you can show the prototype together with its similarity, the name of the prototype, and the index in similarity metric corresponding to each other. If you wanna do global analysis, then you need to take the assignment matrix after GumberSoftmax with the last value of temperature that you used and see which prototypes are lightning up in which slot. 

I hope that this will help!
