### ISSUE TITLE
Local size in PipNet

### ISSUE THREAD

**Issue by ThomasNorr** [gmum/ProtoPool#5]
Hi again,

I have read PipNet (https://openaccess.thecvf.com/content/CVPR2023/papers/Nauta_PIP-Net_Patch-Based_Intuitive_Prototypes_for_Interpretable_Image_Classification_CVPR_2023_paper) and there a local size of all the prototypes is mentioned for ProtoPool (e.g. 202 for CUB). Is that correct?

As far as I understood, you restrict the model to only use 10 prototypes per class ("We set the number of prototypes assigned to each class to be at most 10")?

Best regards

**Comment by dawrym** [comment]
Hello, 

We set the total number of prototypical parts to 202, and each class has 10 slots. So for each class, only 10 prototypical parts are used. 

Best, 
Dawid

**Comment by ThomasNorr** [comment]
Alright, thanks :+1: 
So Table 1 in the paper is inaccurate :I
